### ISSUE TITLE
Can we download from non RSE sites?

### ISSUE THREAD

**Issue by JoranAngevaare** [XENONnT/admix#16]
* aDMIX version: admix.__version__: '0.2.0'
* Python version:  Python 3.6.12 at /opt/XENONnT/anaconda/envs/XENONnT_development/bin/python
* Operating System: dali / linux?

### Description
I wanted to download some peaklets on dali using admix download. It said that the data was not in the US (but the rundoc says it is).

### What I Did
```
(XENONnT_development) [angevaare@dali-login1 test]$ admix-download 010038 peaklets
This run is not in the US so can't be processed here. Exit 255
```
The reason is line:
https://github.com/XENONnT/admix/blob/master/admix/download.py#L31
Can we not just return data also if it is not in the US? Or provide the rse site where it is available?

**Comment by ershockley** [comment]
Thanks for pointing this out @jorana! This was legacy from the 1T processing days where this code was copied from. I will fix now.

**Comment by ershockley** [comment]
Ok it should be fixed in master now. I will rebuild the container later today. I noticed that this does not work for straxen v0.11.1 since the peaklets have not been reprocessed yet -- just a heads up.

**Comment by JoranAngevaare** [comment]
Thanks a lot Evan. 

> I noticed that this does not work for straxen v0.11.1 since the peaklets have not been reprocessed yet -- just a heads up.

This should not be the case unless you are on the straxen master (https://github.com/XENONnT/straxen/pull/271). The eventbuilders are not.

**Comment by ershockley** [comment]
Ah, uh oh. That means I messed up the context update. Now will fix that

**Comment by JoranAngevaare** [comment]
another reason for us to make a new release of straxen and have both eb and everything else go to the new release

**Comment by ershockley** [comment]
Okay context collection is updated (properly) now. I can download peaklets.
